substitutions:
  name: deye-inverter
  friendly_name: "Deye Inverter"
  device_description: "Deye Inverter SG0XLP1"
  modbus_controller_id: deye_modbus_controller
  baud_rate: "9600"
  network_mode: "wifi"
  ethernet_manual_ip_enabled: false
  ethernet_use_address_enabled: false
  ethernet_clk_pin: GPIO15
  ethernet_mosi_pin: GPIO13
  ethernet_miso_pin: GPIO14
  ethernet_cs_pin: GPIO16
  ethernet_interrupt_pin: GPIO12
  ethernet_reset_pin: GPIO39
  ethernet_static_ip: 192.168.1.50
  ethernet_gateway: 192.168.1.1
  ethernet_subnet: 255.255.255.0
  ethernet_dns1: 1.1.1.1
  ethernet_dns2: 8.8.8.8
  ethernet_use_address: 192.168.1.50
  network_wifi_package: !include packages/network_wifi.yaml
  network_ethernet_package: !include packages/network_ethernet_w5500.yaml
  network_ethernet_manual_ip_package: !include packages/network_ethernet_manual_ip.yaml
  network_ethernet_use_address_package: !include packages/network_ethernet_use_address.yaml
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "130" # Amps
  default_max_sell_power: "6000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"

packages:
  - !include packages/init.yaml
  - ${ network_mode == "ethernet" and network_ethernet_package or network_wifi_package }
  - ${ network_mode == "ethernet" and ethernet_manual_ip_enabled and network_ethernet_manual_ip_package or {} }
  - ${ network_mode == "ethernet" and ethernet_use_address_enabled and network_ethernet_use_address_package or {} }
  - !include packages/deye_hybrid_1p/battery.yaml
  - !include packages/deye_hybrid_1p/gen.yaml
  - !include packages/deye_hybrid_1p/grid.yaml
  - !include packages/deye_hybrid_1p/load.yaml
  - !include packages/deye_hybrid_1p/work_mode.yaml
  - !include packages/deye_hybrid_1p/device.yaml
  - !include packages/deye_hybrid_1p/inverter.yaml
  - !include packages/deye_hybrid_1p/pv.yaml
  - !include packages/deye_hybrid_1p/tou.yaml

script:
  - id: set_safe_modbus_registers
    then:
      - logger.log:
          level: INFO
          format: "Setting safe Modbus register values"
      - number.set:
          id: maximum_battery_charge_current
          value: ${default_maximum_battery_charge_current}
      - number.set:
          id: max_sell_power
          value: ${default_max_sell_power}
      - select.set:
          id: system_work_mode
          option: ${default_system_work_mode}
      - switch.turn_${default_solar_sell}:
          id: switch_solar_sell
